import os
from dotenv import load_dotenv

load_dotenv()

# Vtex
VTEX_ACCOUNT_NAME = os.environ.get("VTEX_ACCOUNT_NAME")
VTEX_ENVIRONMENT = os.environ.get("VTEX_ENVIRONMENT")
VTEX_KEY = os.environ.get("VTEX_KEY")
VTEX_TOKEN = os.environ.get("VTEX_TOKEN")
VTEX_API_HOST = f"https://{VTEX_ACCOUNT_NAME}.{VTEX_ENVIRONMENT}.com.br/api"

# BigQuery
BIGQUERY_API_HOST = os.environ.get("BIGQUERY_API_HOST")
BIGQUERY_DATASET_ID = os.environ.get("BIGQUERY_DATASET_ID")
BIGQUERY_SECRET_KEY_ID = os.environ.get("BIGQUERY_SECRET_KEY_ID")
BIGQUERY_SECRET_KEY = os.environ.get("BIGQUERY_SECRET_KEY")
BIGQUERY_CLIENT_EMAIL = os.environ.get("BIGQUERY_CLIENT_EMAIL")
BIGQUERY_JWT_TOKEN_EXP = os.environ.get("BIGQUERY_JWT_TOKEN_EXP")
BIGQUERY_API_TOKEN = os.environ.get("BIGQUERY_API_TOKEN")
BIGQUERY_SERVICE_ACCOUNT = ""