name: Deploy Gauss Scripts to Google Cloud Functions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud with a Service Account Key
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Deploy load_orders_data Function
      uses: google-github-actions/deploy-cloud-functions@v2
      with:
        name: 'load-vtex-orders-data'
        runtime: 'python310'
        entry_point: 'run'
        source_dir: './modules/vtex/orders'
        region: 'southamerica-east1'
        https_trigger_security_level: 'secure_always'
        project_id: 'gaussgrowth'
        env_vars: VTEX_KEY=${{ secrets.VTEX_KEY }}, VTEX_TOKEN=${{ secrets.VTEX_TOKEN }}, VTEX_ENVIRONMENT=${{ secrets.VTEX_ENVIRONMENT }}, VTEX_ACCOUNT_NAME=${{ secrets.VTEX_ACCOUNT_NAME }}